### ISSUE TITLE
Matrix Concatination

### ISSUE THREAD

**Issue by Beakerboy** [mcordingley/LinearAlgebra#28]
It would be nice to have two concatenation methods, one to add additional columns, and one to add additional rows.

    $M1 = new Matrix ([
      [1,2,3],
      [4,5,6],
    ];

    $M2 = new Matrix{[
      [7],
      [8],
    ];
    $M3 = new Matrix([[3,2,1]]);

    $M4 = $M1->concatinateRight($M2);
     //[[1,2,3,7],
    //  [4,5,6,8]]

    $M5 = $M1->concatinateBottom($M3);
      //[[1,2,3],
      // [4,5,6],
      // [3,2,1]]

**Comment by mcordingley** [comment]
I don't see why not. I'll put it in my to-do queue. Are you stacking up
vectors together or something?

**Comment by Beakerboy** [comment]
When doing multiple linear regression, the first column in the array needs to have a full columns of '1' to allow for the intercept. I want to just send an array of my independent variables, and have the regression function tack on the ones column, unless doing regression through the origin.

**Comment by Beakerboy** [comment]
I can imagine someone eventually will want an 'extract' method to pull out an individual row or column. These could probably be extended to extracting several adjoining rows or columns, or splitting the matrix in two parts at a specific position.

**Comment by mcordingley** [comment]
I like the general idea. It could probably be made more general with a start and end index to pull out a sub-matrix. I'll wait until someone puts in that request with a specific use case in mind so I know the general shape of intended use.

**Comment by mcordingley** [comment]
Enjoy!

**Comment by mcordingley** [comment]
I just published a new release (1.3.0) that fixes a typo in these methods. You should update when you have a chance. Also note the deprecations in the new version.
