### ISSUE TITLE
map function in matrix class have bug.

### ISSUE THREAD

**Issue by battlecook** [mcordingley/LinearAlgebra#32]
map function return "new static()"

but vector and matrix construct is different.

if vector class use map function, internal variable is wrapped by array one more.

for example, following test case is failed

public function testGetAfterUseMatrixFunction()
{
    $vector1 = new Vector([1, 1]);
    $vector2 = new Vector([3, 2]);
    $this->assertEquals(4, $vector1->addMatrix($vector2)->get(0,0));
}

**Comment by mcordingley** [comment]
I'll follow up on this as soon as I get a moment. It's crunch time right now for work.

**Comment by mcordingley** [comment]
Nice catch. Tagging a bug-fix release now and I think I may need to add some additional vector functions to handle adding and subtracting them. Otherwise, the user will have to continually cast matrices to vectors.
